package com.example.Spring.application.bet;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.example.Spring.application.bet.commands.PlaceBetCommand;
import com.example.Spring.domain.bet.Bet;
import com.example.Spring.domain.bet.Bet.BetId;
import com.example.Spring.domain.bet.ports.BetRepository;

@Service
public class BetCommandService {
    private final BetRepository betRepository;

    public BetCommandService(BetRepository betRepository) {
        this.betRepository = betRepository;
    }

    @Transactional
    public Bet.BetPlaced placeBet(PlaceBetCommand command) {
        var bet = Bet.place(
            new BetId(null), // Will be generated by the repository
            command.matchId(),
            command.userId(),
            command.teamId(),
            command.amount(),
            command.coefficient()
        );
        
        bet = betRepository.save(bet);
        return new Bet.BetPlaced(bet.getId(), bet.getUserId(), bet.getAmount());
    }

    @Transactional
    public Bet.BetWon winBet(BetId betId) {
        var bet = betRepository.findById(betId)
            .orElseThrow(() -> new IllegalArgumentException("Bet not found"));
        
        var event = bet.win();
        betRepository.save(bet);
        return event;
    }

    @Transactional
    public Bet.BetLost loseBet(BetId betId) {
        var bet = betRepository.findById(betId)
            .orElseThrow(() -> new IllegalArgumentException("Bet not found"));
        
        var event = bet.lose();
        betRepository.save(bet);
        return event;
    }
} 